# Generated by Django 4.1.3 on 2022-11-27 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
